[package]
name = "web_scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
openssl-sys = { version = "0.9", features = ["vendored"] }
openssl = { version = "0.10", features = ["vendored"] }
reqwest = { version = "0.11", features = ["blocking"] }
scraper = "0.15"
tokio = { version = "1", features = ["full"] }

